### ISSUE TITLE
Revisar responsividad

### ISSUE THREAD

**Issue by jforni** [NachoGuardo1/RollingTech#65]
Revisar responsividad, la probé en dos pantallas distintas y hay diferencias con respecto a como se ve el carrusel en cada una.

![image](https://github.com/NachoGuardo1/RollingTech/assets/6042663/bc7ff8fb-a5b1-4354-a4c9-3da94c2daff9)
![image](https://github.com/NachoGuardo1/RollingTech/assets/6042663/d1d02abb-e543-473a-8c2e-79e6fb1a0608)

**Comment by NachoGuardo1** [comment]
solucionado
