### ISSUE TITLE
Imagenes del carrusel de distinta altura

### ISSUE THREAD

**Issue by jforni** [NachoGuardo1/RollingTech#66]
Revisar el tamaño de las imágenes del carrusel de la página principal. Varían en el alto.

![image](https://github.com/NachoGuardo1/RollingTech/assets/6042663/02615fdb-5dfc-47cb-b6aa-7d4fe0ee167c)
![image](https://github.com/NachoGuardo1/RollingTech/assets/6042663/91df7248-ca7d-490d-bde7-48fe987b5dd1)

**Comment by NachoGuardo1** [comment]
Solucionado
